// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CompareFiles(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Results>;

export function DebugMe(arg1:string):Promise<void>;
