// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompareFiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CompareFiles'](arg1, arg2, arg3, arg4);
}

export function DebugMe(arg1) {
  return window['go']['main']['App']['DebugMe'](arg1);
}
